export const prompts = [
  " i bear witness that ",
  "there is no god but Allah",
  "and I bear witness that ",
  "Muhammad is the Messenger of God",
  "ash hadoe",
  "an la",
  "elah",
  "ela",
  "alah",
  " wa ",
  "ash hado",
  "ana",
  "mohamed",
  "rasoul",
  "alah",
];
